### ISSUE TITLE
pygraph error

### ISSUE THREAD

**Issue by CPernet** [CPernet/metaprivBIDS#1]
I'm not sure where the error comes from at compilation -- miniconda or our baseline server ?? but then we use venv so should be the case ...

running from NRU server the install fails with this error
 gcc -pthread -B /usr/local/miniconda/20220815/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /usr/local/miniconda/20220815/include -fPIC -O2 -isystem /usr/local/miniconda/20220815/include -fPIC -DSWIG_PYTHON_STRICT_BYTE_CHAR -I/indirect/openneuropet/metapriv/include -I/usr/local/miniconda/20220815/include/python3.9 -c pygraphviz/graphviz_wrap.c -o build/temp.linux-x86_64-3.9/pygraphviz/graphviz_wrap.o
      pygraphviz/graphviz_wrap.c:3020:10: fatal error: graphviz/cgraph.h: No such file or directory
       #include "graphviz/cgraph.h"
                ^~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pygraphviz

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by EmiKib** [comment]
As I can see, it is a system-level dependencies so it also fails in a virtual environment. Maybe I can solve it by dockerizing the project. I am working on a solution. 

does running:

sudo apt-get install graphviz graphviz-dev

work?

**Comment by EmiKib** [comment]
![Uploading Screenshot 2024-10-03 at 14.18.03.png…]()
